services:
  backend:
    build:
      context: ./backend
      target: development
      # target: production
      dockerfile: Dockerfile
    # Development only
    volumes:
      - ./backend:/app:delegated
    ports:
      - "4000:4000"
    # Development only
    command: npx nodemon --watch src --exec ts-node src/index.ts
    environment:
      - NODE_ENV=development
      # - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      target: development
      # target: production
      dockerfile: Dockerfile
    # Development only
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    # Development only
    command: npm run dev
    environment:
      - NODE_ENV=development
      # - NODE_ENV=production
